name: Deploy Image Resizer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   # Change to your region

    - name: Sync Images to S3
      run: |
        aws s3 sync images/ s3://image-upload-1999/images/

    - name: Deploy Lambda
      run: |
        zip -j lambda.zip lambda/index.js
        aws lambda update-function-code --function-name AutoResizeImage --zip-file fileb://lambda.zip
